### ISSUE TITLE
Instruction BGT and BLE on Processing Emulator

### ISSUE THREAD

**Issue by michaelkamprath** [slu4coder/The-Minimal-64-Home-Computer#10]
In the reference manual for the Minimal 64, instruction `BGT` is documented to have byte code `98` and `BLE` is documented to have byte code `97`. However, in [the Processing Minimal 64 emulator](https://github.com/slu4coder/The-Minimal-64-Home-Computer/blob/main/Support/Emulator/Processing/Minimal_64_Emulator/Minimal_64_Emulator.pde#L714-L725), `BGT` is `97` and `BLE` is `98`. 

Which one is right? I am not in a position to test on hardware, which I would consider to be the "right" one. I am also not in a position to test the Windows emulator, so I don't know how that one behaves.

It is also worth noting that the microcode in the documentation doesn't have the `BGT` or `BLE` implementation (or any conditional branch for that matter).

Note this took me forever to figure out that it was not my code that was wrong but that the emulator and the documentation were not aligned.

**Comment by michaelkamprath** [comment]
FWIW, I checked the various assemblers' code you have produced (python, C++, native) and they all have `BGT` is 97 and `BLE` is 98. I am going to assume that this is a bug in the reference manual.

**Comment by slu4coder** [comment]
Hi Michael,
you've found a typo in the manual. I can confirm that BGT = 97 and BLE = 98. All emulators, assemblers and control ROMs are consistently using that definition. As you have pointed out, it is a typo in the reference manual alone (mirrored in the onboard user manual "manual.txt" which is displayed when entering 'show manual ENTER' on the Minimal 64). I am grateful for the time and effort you have put into this issue. Thanks! I have corrected the issue in the manual and manual.txt.
An updated flash.bin will follow tomorrow.
