### ISSUE TITLE
Is there a Minimal 64 Home Computer forum

### ISSUE THREAD

**Issue by denjhang** [slu4coder/The-Minimal-64-Home-Computer#11]
I'm about to build hardware for Minimal 64, like last year's Minimal UART CPU, is there a forum? Recently I found out that the forum for Minimal UART CPU is closed.

**Comment by slu4coder** [comment]
Hi, great to hear you are going to give the 'Minimal 64' a try, too. It is basically a Minimal UART on steroids ;-) As of today, I am not planning to continue the forum for the Minimal 64. It is just too confusing for me as a one-man show. Let's either use GitHub issues or plain old email. Don't forget to send me a picture of your build to secure your place and serial number in the 'Gallery' section of the Minimal 64 Manual :-)

**Comment by michaelkamprath** [comment]
@slu4coder If I might suggest, you could enable GitHub discussions for this repository. It's a discussion board for this repository. The issue with issues is that they are design to be "closed" and once closed, it's hard for people to learn from the discussion. 

See this: https://github.com/features/discussions

**Comment by slu4coder** [comment]
GitHub discussions activated :-)
