### ISSUE TITLE
"show" output incomplete

### ISSUE THREAD

**Issue by fdziarmagowski** [slu4coder/The-Minimal-64-Home-Computer#18]
Try "show lines.min", in the first line "se" instead of "use" will be shown.

**Comment by slu4coder** [comment]
Presently, 'show' is intended to display text documents *only* in the special format (% for page breaks) used by 'manual'. 'show' should not be used to display arbitrary text data, e. g. source code. Please use 'edit <textfile>' instead.

I know, this is a bit counter-intuitive and I might improve the 'show' command in the future.

**Comment by slu4coder** [comment]
I have rewritten the 'show' command to both display source files and the manual page-wise in an intuitive way. The files manual.txt, os.asm and flash.bin have been updated.

**Comment by fdziarmagowski** [comment]
This is awesome! I just translated "show" to "cat" at my fingertips, automagically expecting it will work on any file. This blind assumption was of course incorrect.

**Comment by slu4coder** [comment]
If you want to change the names of OS commands in os.asm sourcecode, always make sure you edit the file header correctly, i. e. inserting zeros after the name when you make it shorter helps 😀
