### ISSUE TITLE
TTL games

### ISSUE THREAD

**Issue by ghost** [slu4coder/The-Minimal-64-Home-Computer#22]
hi

I try to learn how to make TTL games like they were made in the 70s.
Do you know example games, old books or websites?

**Comment by cakesmith** [comment]
I was looking specifically for the space invaders source. Thanks for such an awesome project! I just discovered this yesterday and I'm already smitten. The scan lines in the emulator are sublime.

**Comment by slu4coder** [comment]
Hey ghost, cakesmith,
welcome to the Minimal 64. Glad you like this stuff ;-) Be aware though, that my Space Invaders clone is not a 1 to 1 port but rather my personal adaptation. I think I got it quite close, though ;-)

I do not know nor do I use any particular literature or books. TTL games are all about building something that it fun (or was considered being fun during the 70's ;-) and runs on very limited hardware. That was my motivation to build the Minimal 64 TTL Computer. I combines this closeness to the hardware and minimalism with quite some computational power.

**Comment by slu4coder** [comment]
Btw, there is also a 'Discussions' section on this repo. Let's move over there since this is not a software or hardware issue...
