### ISSUE TITLE
Is it possible to provide a US keyboard layout version of the Flash ROM file?

### ISSUE THREAD

**Issue by denjhang** [slu4coder/The-Minimal-64-Home-Computer#24]
I want to change the keyboard layout, I use US keyboard, but when I use receive, the transmission always goes wrong.
So I hope to burn the US keyboard layout into ROM directly through the programmer instead of using UART.

**Comment by slu4coder** [comment]
I have uploaded a version of 'flash.bin' with pre-installed US keyboard layout I have renamed to  'flash_us.bin'.

If you find yourself unable to update via UART there is still a problem within you circuit worth debugging. On my system, upload via UART does not produce any checksum errors.
