### ISSUE TITLE
Does min language lack exponentiation function?

### ISSUE THREAD

**Issue by denjhang** [slu4coder/The-Minimal-64-Home-Computer#25]
I try to write e.g.
i=4^i
As a result, min complained that it could not be recognized.
Many floating point basics support ^ as the exponentiation symbol.

**Comment by michaelkamprath** [comment]
I can only imagine that the Min language is, well, _minimal_. The [EBNF for Min](https://github.com/slu4coder/The-Minimal-64-Home-Computer/blob/main/Programs/min/MIN's%20EBNF%20language%20definition.txt) clearly does not define a exponent operator. However, [the code for Min is open](https://github.com/slu4coder/The-Minimal-64-Home-Computer/blob/main/Programs/asm/min.asm), I'm sure some adventurous programmer could contribute improvements.

**Comment by slu4coder** [comment]
Hi guys,
no floating point, no exponential function in Min, sry. Min - as vehicle to understand interpreters - is strictly 16bit integer.
Cheers!
