### ISSUE TITLE
Min language does not support floating point numbers?

### ISSUE THREAD

**Issue by denjhang** [slu4coder/The-Minimal-64-Home-Computer#26]
Many retro computers support floating point basic, so you can calculate pi. I hope min language can support floating point numbers.

**Comment by slu4coder** [comment]
No floating point, no exponential function in Min, sry. Min - as vehicle to understand interpreters - is strictly 16bit integer.
I suggest you experiment with fixed-point numbers. They can easily be implemented in low-level languages. See Michael's Mandelbrot demo for a nice example.
Cheers!
