### ISSUE TITLE
Missing source code for 'asm.exe' assembler

### ISSUE THREAD

**Issue by nb-programmer** [slu4coder/The-Minimal-64-Home-Computer#7]
I couldn't find the source code of the Windows assembler inside [Programs/asm](https://github.com/slu4coder/The-Minimal-64-Home-Computer/tree/main/Programs/asm), just the final binary. Can you add the source as well? This may help with improving it

**Comment by slu4coder** [comment]
If you are interested in the assembler, please have a look at programs/asm/asm.py file, the 60-lines Python source code of the very same assembler. There is also a video about it. The file expresses much more clearly the inner workings of the assembler. I might add the C++ source at a later time but it takes so much more code to express the functionality as compared to Python.

**Comment by nb-programmer** [comment]
Okay alright
Thanks!

**Comment by nb-programmer** [comment]
Thank you!
