### ISSUE TITLE
What is the FF flag?

### ISSUE THREAD

**Issue by michaelkamprath** [slu4coder/The-Minimal-64-Home-Computer#8]
The microcode definitions for the X, Y, and stack interactions have a microcode flag called `FF`. I don't readily see in the schematic that that flag is. I suspect it is just a conceptual placeholder that does nothing, thus the data base has a 0xFF value on it due to the pull up resistors, but we don't have access to the microcode compiler to confirm that. Any insight here would be appreciated.

**Comment by slu4coder** [comment]
FF is not a physical control signal or flag. As you have guessed correctly, I use it as a placeholder for "all control signals inactive". Whenever you see "FF" in the microcode, 0xFF (-1) is present at the bus. As trivial as this feature looks, "FF" appears in 139 microcode positions across the entire instruction set and is *the* key for most if not all of the advanced instructions of the CPU.
