### ISSUE TITLE
AS6C1008 SRAM "64KB"?

### ISSUE THREAD

**Issue by michaelkamprath** [slu4coder/The-Minimal-64-Home-Computer#9]
The BOM in the user manual for the Minimal 64 describes U13 as `AS6C1008_SRAM_64KB`, however, the `AS6C1008` is a 128K RAM chip. Is the "64KB" in the BOM description a typo, the wrong chip, or is it just indicating how much of the `AS6C1008` is actually being used?

**Comment by slu4coder** [comment]
Thanks for pointing out this potential pitfall. I am indeed using AS6C1008, i. e. a 128K SRAM chip.

The Minimal, being a 16-bit machine, only addresses 64KB of it.
In the schematic A16 (Pin 2 of U13) is grounded. I will correct it in the BOM to avoid confusion.
